Odoo10Testing:
  image: kdvn/odoo
  container_name: odoo
  ports:
   - "8980:8069"
  volumes:
   - ./addons:/mnt/extra-addons
   - ./odoodata:/opt/odoodata
   - ./workspace:/opt/workspace
  links:
   - odoo_db:db
  environment:
   - PGHOST=odoo_db
   - PGUSER=odoo
   - PGPASSWORD=odoo
   - AUTH=admin:admin
   - LOCAL_USER_ID=1000
odoo_db:
  image: postgres:latest
  container_name: odoo_db
  volumes:
    - ./db:/var/lib/postgresql/data
  environment:
   - POSTGRES_USER=odoo
   - POSTGRES_PASSWORD=odoo
