Odoo10Testing:
  image: kdvn/odoo-c9
  container_name: odoo-c9
  ports:
   - "8180:8069"
   - "88:3000"
  volumes:
   - ./addons:/mnt/extra-addons
   - ./filestore:/mnt/oefilestore
   - ./workspace:/opt/workspace
  links:
   - odoo_db:db
  environment:
   - PGHOST=odoo_db
   - PGUSER=openerp
   - PGPASSWORD=openerp
   - AUTH=admin:admin
   - LOCAL_USER_ID=Please input manually using (user - id -u $USER)
odoo_db:
  image: postgres:latest
  container_name: odoo_db
  environment:
   - POSTGRES_USER=openerp
   - POSTGRES_PASSWORD=openerp
